# FIX: MAYBE: Alacritty cannot recognize `Shift + Enter`
# | https://github.com/alacritty/alacritty/issues/7256
# | ^ looks like it may be fixable, but I've moved to Kitty already

import = ["~/.config/alacritty/themes/kanagawa.toml"]

[font]
size = 12.3

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Normal"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[mouse]
hide_when_typing = true

[window]
decorations = "full"
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 24
